### PR TITLE
Scrap Marty.Component in favour of Marty.createContainer

### LINKED ISSUE #204: Scrap Marty.Component in favour of Marty.createContainer
FB just blogged about how [Relay works](http://facebook.github.io/react/blog/2015/03/19/building-the-facebook-news-feed-with-relay.html).

This makes a lot of sense and gets around a load of the issues with ``Marty.Component`` (e.g. contextTypes, having to inherit from a base class). 

I suggest we scrap ``Marty.Component`` altogether and just replicate ``Relay.createContainer``

```js
class User extends React.Component {
  render() {
    return this.props.user.when({
       ...
    });
  }  
}

module.exports = Marty.createContainer(User, {
  listenTo: UserStore,
  user() {
    return UserStore.getUser(123)
  }
});
```

### PR DESCRIPTION
**Pull request by jhollingworth**
FB just blogged about [how Relay works](http://facebook.github.io/react/blog/2015/03/19/building-the-facebook-news-feed-with-relay.html). This makes a lot of sense and gets around a load of the issues with ``Marty.Component`` (e.g. ``contextTypes``, having to inherit from a base class). This PR gets rid of ``Marty.Component`` and replicates the ``Relay.createContainer`` API.

```js
module.exports = Marty.createContainer(User, {
  listenTo: [UserStore, FriendsStore],
  fetch: {
    user() {
      return UserStore.getUser(this.props.id)
    },
    friends() {
      return FriendsStore.getFriends(this.props.id)
    }
  },
  // optional
  done(fetches, component) {
    return <User {...fetches} {...component.props} />
  },
  // when any of the fetches have failed
  failed(error, component) {
    return <Error />;
  },
  // when any of the fetches are pending
  pending(component) {
    return <User user={{}} {...component.props}/>;
  }
});
```

**To do**

* [x] Rename container to registry
* [x] Create ``Marty.createContainer``
  * [x] failed
  * [x] done
  * [x] pending
* [x] Get rid of ``Marty.Component``
* [x] Update all examples of using ``Marty.Component``

Resolves #204

### CODE REVIEW

**Comment by jhollingworth** [comment]
See also https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

**Comment by dariocravero** [comment]
:+1: came here to suggest just that and spotted this PR.

Totally on for dropping `Marty.Component` in favour of this approach, it makes lots of sense to get away from a custom Component class :).
Also, good call on renaming `Container` to `Registry` and having `done`, `failed` and `pending` at the container level, I'd imagine that the object comes clean to the `Component` without any `when` stuff?

Quick one, looking at the source, shouldn't the example read like this?

```js
//...
  fetch: {
    user: () => {
      return UserStore.getUser(this.props.id)
    }
  },
//...
```

or, for the mandatory one-liner :D:

```js
//...
  fetch: {
    user: () => UserStore.getUser(this.props.id)
  },
//...
```

It might also be a good idea to keep `Relay` semantics in place? So instead of calling it `fetch` it could be named `queries`? I know that Marty [queries](http://martyjs.org/v/0.9.0-rc2/guides/queries/index.html) kind of do a different thing but still, maybe it's out of question but perhaps Marty queries could be renamed instead?

**Comment by pbomb** [comment]
We have some container components (view-controllers) in Marty v0.8 where some of the fetches depend on the results other ones. I like the convenience of this proposed API, but it doesn't allow for fetches to depend on others or for possibly more complicated behavior. How about only putting your implementation of getState on the container (which puts each fetch on the state) if there's not already a getState function defined on the config object? Then I can continue to use an implementation for getState like I already do for the v0.8 StateMixins for these situations.

**Comment by jhollingworth** [comment]
@dariocravero awesome, glad you like it :smile: I'd like to keep the ``fetch`` keyword for now as I'd like to leave the door open for integrating with relay in the future

**Comment by jhollingworth** [comment]
@pbomb How about if I allowed fetch to either be a function or an object literal containing functions? 

```js
module.exports = Marty.createContainer(User, {
  fetch() {
    return {
      user: UserStore.getUser(this.props.id),
      friends: FriendsStore.getFriends(this.props.id)
    }
  }
});
```

**Comment by pbomb** [comment]
Yeah, I thought about that too. I like it!

**Comment by jhollingworth** [comment]
cool, implemented in 4ce9143

**Comment by dariocravero** [comment]
Class ;)

**Comment by pbomb** [comment]
It would be great to be able to specify the display name is the container component, either by padding or in our by adding 'Container' to the display name of the inner component. We like to record metrics and these names are helpful.

**Comment by jhollingworth** [comment]
@pbomb would "{InnerComponentDisplayName}Container" be fine? e.g. ``FooContainer``

**Comment by pbomb** [comment]
I think so

**Comment by jhollingworth** [comment]
@pbomb 718dafb

**Pull request merged**
