### PR TITLE
Better error handling

### LINKED ISSUE #163: Simplify error handling
How action creators work, in particular error handling is a recurring issue (#157, #152, #127) we need to solve. Having the action creators automatically dispatch ``ACTION_{type}`` errors seemed like a neat idea at the time but it's not very useful and has lead to a load of complicated code and crappy APIs.

I think we should just go back to a simpler, explicit approach ([Yahoo has some good examples](https://github.com/yahoo/flux-examples/blob/master/chat/actions/createMessage.js)):

* No more dispatching ``ACTION_{type}`` errors
* Don't wrap action creator functions in promises
* Explicit error handling

```js
var FooActionCreators = Marty.createActionCreators({
  createFoo(foo) {
    this.dispatch(Constants.RECIEVE_FOO, foo);

    FooAPI.createFoo(foo).catch((error) => {
      this.dispatch(Constants.RECIEVE_FOO_FAILED, foo, error);
    });
  }  
});
```

As much as I'd like to have some [automatic error handling/retrying](http://ianobermiller.com/blog/2014/09/15/react-and-flux-interview/) I think we should get the simple case right first.

### PR DESCRIPTION
**Pull request by jhollingworth**
This PR should fix #163, #157, #152 and #127 which I'm hoping will make everything a lot better

**Changes**

* To dispatch an action you use ``this.dispatch(ACTION_TYPE, ...args)``
* You can now dispatch from [state sources eliminating the need for source action creators](https://github.com/jhollingworth/marty/blob/error-handling/docs/_guides/state-sources/dispatching-actions-from-state-sources.md)
* Action creators are no longer wrapped in a promise so error handling should be easier
* We no longer dispatch ``{Action Type}_STARTING``, ``{Action Type}_DONE`` or ``{Action Type}_FAILED``. Instead ``Marty.createConstants`` will automatically create ``{Action Type}_STARTING``, ``{Action Type}_DONE`` or ``{Action Type}_FAILED`` as well as ``{Action Type}`` constants for you
* We don't proxy action creators which makes stepping through code easier
* The old invokable constants style still works but is depreciated. I've added [documentation about how to migrate](https://github.com/jhollingworth/marty/blob/error-handling/docs/_guides/action-creators/migrating-from-v8.md)
* I've added some [documentation about how to handle errors](https://github.com/jhollingworth/marty/blob/error-handling/docs/_guides/action-creators/handling-errors.md) (Could do with expanding upon a bit)

### CODE REVIEW

**Comment by mickhansen** [comment]
In one example you are dispatching DONE/FAILED in the actionCreator, in another you do it from the state source (whether that be via source action creators or dispatching directly). What's the rule of thumb for seperation here? Writes are handles by the actionCreators and fetches are handled by the state sources?

**Comment by jhollingworth** [comment]
@mickhansen you're right, the distinction is reads and writes.

Up to now we've had the concept of [source action creators](http://martyjs.org/guides/action-creators/source-action-creators.html) which are responsible for handling state changes. I've always felt its a bit over kill to have a whole file just to get around a cyclic dependency issue so thought it would make sense to allow state sources to be able dispatch their own actions.

What do you think? Does it make sense to you?

**Comment by mickhansen** [comment]
@jhollingworth they do feel a bit of overkill. Whether or not it's perfect Flux design i couldn't possible comment on.

I think it makes sense seperating writes and reads like that, although ideally from a CQRS standpoint you probably wouldn't want writes and reads mixed in the state source, but i think this way is a bit more terse and workable.

It's taken me a good while to wrap my head around Flux and the ideas imposed by Flux even by using a good a framework as Marty, so it might be worth pointing out how writes and read success/fail handling is "supposed to be" in Marty.

**Comment by AlanVerbner** [comment]
@jhollingworth Will I be able to parse error response body? I'm asking because in version 0.8.X the service I'm consuming returns in the body the list of errors as JSON. When response status is >= 400 is not parsed:

```javascript
return fetch(options.url, options).then(function (res) {
  if (res.status >= 400) {
    throw res;
  }

  if (isJson(res)) {
    return res.json().then(function (body) {
      res.body = body;

      return res;
    });
  }

  return res;
});
```

and i get undefined if I try to do something like:

```javascript
.catch(function (res) {
      return UsersActionCreators.serverError(res);
 });
```

Am I doing something wrong? What's the correct approach to get data from the body? Will this be changed with your commits (i haven't found the >=400 check)?

**Comment by jhollingworth** [comment]
@AlanVerbner yeah, thats completely gone in v0.9. We're also going to be introducing [hooks](https://github.com/jhollingworth/marty/blob/v0.9/docs/_api/state-sources/http.md#hooks) which will allow you to modify http requests before their sent and responses before their passed on

**Comment by jhollingworth** [comment]
@mickhansen completely agree with you on splitting out reads/writes à la CQRS. If I could find a terse way of doing this that I'd be really keen.

Either way I will add something to the guide about reading and writing

**Comment by jhollingworth** [comment]
So one thing we could do is introduce the concept of 'Queries' which are responsible for orchestrating requests to get data.

```js
var UserQueries = Marty.createQueries({
  getUser(id) {
    return this.get('/users')
     .then((res) => this.dispatch(UserConstants.RECIEVE_USERS, res.body))
     .catch((err) => this.dispatch(UserConstants.RECIEVE_USERS_FAILED, err));
  }
});

var UserStore = Marty.createStore({
  recieveUser(user) {
    this.state[user.id] = user;
    this.hasChanged();
  }
  getUser(id) {
    this.fetch({
      id: id,
      locally() {
        return this.state[id];
      },
      remotely() {
        return UserQueries.getUser(id);
      }
    })
  }
})
```

They are pretty much identical to action creators however they help enforce the difference between reads (queries) and writes (actions). It also allow us to get around the cyclic dependency without having 'source action creators'. 

Also, it would be interesting to prevent you from returning anything from an action creator to help enforce the notion that action creators are for propagating state through the dispatcher.

What do you think?

**Comment by mickhansen** [comment]
@jhollingworth I think that could make a lot of sense. It also allows complete decoupling of the state source - And allow you to use whatever data layer you'd like.

**Pull request merged**
