### PR TITLE
Repositories

### PR DESCRIPTION
**Pull request by oliverwoodings**
Still have a few things to do but just want to check I'm on the right lines.

To do:

* [x] Tests
* [x] HttpRepository
* [ ] Docs

### CODE REVIEW

**Comment by KidkArolis** [comment]
DataSource
Connector
Storage
Persistance

Actually, Ember Data uses "adapters". They have stores and adapters.
https://github.com/emberjs/data/blob/master/README.md

**Comment by jhollingworth** [comment]
I like DataSource

```
var UserDataSource = Marty.createDataSource({
  type: 'http',
  createUser: function (user) {
    this.post('/users', user);
  }
});
```

**Comment by KidkArolis** [comment]
The only issue with it is that it also sounds a bit like a store.
I think my vote is on adapter, since it sounds distinct from store. And it
adapts/maps some back end store or api to the marty store.

**Comment by jhollingworth** [comment]
I quite like the word "source" ("a place, person, or thing from which something originates or can be obtained."). Would it be less store-ish if we used the word state? State is used through out Marty & react so makes sense to use the same terminology

```
var UserAPI = Mart.createStateSource({
  type: "http",
  createUser: function (user) {
    this.post('/users', user);
  }
})
```

**Comment by jhollingworth** [comment]
I sort of feel adapters are an underlying concept (i.e. what a state source uses)

**Comment by jhollingworth** [comment]
Btw, I've [re-written the documentation](http://martyjs.org/) so it supports [sub pages now](http://martyjs.org/guides/stores/immutable-data-collections.html).

**Comment by oliverwoodings** [comment]
Sorry I haven't replied to this yet - been up and down the country a bit.

As I was developing this I was starting to think the same thing; repositories just doesn't sound right.

@jhollingworth i think you are right in that an adapter is an underlying concept that is used by what we are trying to create here. Right now it is comparable to how a mixin is used in this PR (adds functionality for each method to use).

Source was actually I think what I originally suggested when we started talking about how HttpAPI needed to change. StateSource could work.

**Comment by jhollingworth** [comment]
awesome! I've been [playing around with the concept in Marty Developer Tools](https://github.com/jhollingworth/marty-devtools/blob/master/app/panel/stateSources/columnsStateSource.js) and it seems to work. 

Now that we're being more generic about where state comes from [Server Action Creators](http://martyjs.org/guides/action-creators/server-action-creators.html) don't really work any more. Not sure what to call them...

* StateActionCreators
* SourceActionCreators

Any ideas?

**Comment by oliverwoodings** [comment]
RemoteActionCreators?
ExternalActionCreators?

**Comment by jhollingworth** [comment]
@oliverwoodings how's this stuff going? if you're a bit busy I can help finish this off?

**Comment by oliverwoodings** [comment]
Hey, I've actually got an exam next week so not been able to do much. If
you want to finish it up go ahead :)

**Comment by jhollingworth** [comment]
I'm merged your commits into [state-sources](https://github.com/jhollingworth/marty/tree/state-sources) and opened up #56. You should be a committer to the repo so you can still make changes. 

Best of luck with the exam!

**Pull request closed without merging**
