### PR TITLE
Upgrade React's peer dependency to 0.13.0

### PR DESCRIPTION
**Pull request by dariocravero**

### CODE REVIEW

**Comment by jhollingworth** [comment]
:+1:

**Comment by scottcorgan** [comment]
Any reason this wouldn't work with React 0.14?

**Comment by taion** [comment]
There would be deprecation warnings from not going through `ReactDOM` for the rendering - not sure if that matters to you.

**Comment by scottcorgan** [comment]
Warnings aren't as important as the installation error I see with unresolved peerDependencies from NPM.

Where in Marty does it Call render()?

**Comment by taion** [comment]
`Application.renderToString` and related methods.

**Comment by scottcorgan** [comment]
It looks like `renderToString()` takes a render argument.

Seems possible to pass in from `react-dom`.

I'm not to familiar with then inner workings of `marty` and `marty-lib`, but Perhaps it would be helpful to cut a final `1.0` with support for React 0.14.

**Pull request merged**
