### PR TITLE
Use let instead of var

### PR DESCRIPTION
**Pull request by dariocravero**
As we're embracing ES6 more and more, I think that the first step would be to convert all of those `var`s to `let`s.

I don't know how far we can go with tests though, are the fixtures passed through babel as well? Otherwise we might hit [some incompatibility on older browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Browser_compatibility)... 

Another step forward would be to convert all the `require`s and `export`s to `import Module from 'module'` and `export default Module`, etc. I'm happy to go through it if you're ok with that?

Thoughts?

### CODE REVIEW

**Comment by jhollingworth** [comment]
Happy to do use more ES6 features. My only concern with using ``export`` would be supporting node.js v0.10 when doing isomorphisim.

If its OK I'd like to move these changes to Marty v0.10. I was planning on releasing v0.9 today and don't want to introduce last minute changes

**Comment by dariocravero** [comment]
Sounds good to me :) Great job on `0.9`!

Personally, I think that leaving node `0.10` behind would be a good thing. iojs is saving the day and helping us keep the pace at pushing the boundaries...

Would that be possible in marty `0.10` (what an irony that the version numbers will match :))?
Thanks

**Comment by jhollingworth** [comment]
Still keen to do this but now everythings been split out this PR's can't be merged so going to close

**Comment by dariocravero** [comment]
Agree, it should be done on the separate projects :)

**Pull request closed without merging**
