### PR TITLE
Marty v0.9

### PR DESCRIPTION
**Pull request by jhollingworth**
**Improvements**

* [x] Isomorphism (#13)
  * [x] Add ``Store#dehydrate`` and ``Store#hydrate`` (Replacing ``Store#serialize`` and ``Store#getInitialState(stateFromServer)``)
  * [x] Prevent you from registering multiple instances with the same Id
  * [x] CookieStateSource
    * [x] Implement server side implementation in marty-express
  * [x] LocationStateSource
    * [x] getLocation
    * [x] setLocation
  * [x] Fetch diagnostics (#179)
  * [x] Sync store meta state
* [x] ES6 Classes (#89)
  * [x] ~~Work out if we can stop having to call ``super``~~ Don't think its possible right now, [React has the same problem](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html)
  * [x] Support ``this.state = ..`` instead of ``getInitialState``.
  * [x] Add ``Marty.Component``
* [x] Add ``dataType`` option to http state source (#161)
* [x] Lodash v3 instead of underscore (#136)
* [x] Simplify error handling (#163)
* [x] replaceState and setState (#126)
* [x] HttpStateSource hooks (#118)
* [x] Improved action type definition (#93)
* [x] FetchResult#toPromise (#131)
* [x] Propagate failed fetch through ``FETCH_FAILED`` action (storeId, fetchId, error)
* [x] Improve warnings (#154)
* [x] Make React a peer dependency
* [x] Clear fetch history in ``Store#clear`` (#149)
* [x] Batch store on change events (#112)
* [x] Allow you to specify when function context (#76)
* [x] Copy & paste state (see [marty-clipboard](https://github.com/jhollingworth/marty-clipboard))
* [x] ~~Routing~~ Will release this separately
* [x] Scrap Marty.Component in favour of Marty.createContainer
* [x] Warn when failed to resolve context and not default instance
* [x] Make hook order optional
* [x] Make container displayName "{InnerComponent}Container"
* [x] Call ``Store#getInitialState`` in clear if present

**Bugs**

* [x] IE <= 10 tests failing
* [x] dehyrdated FetchHistory is at wrong level 
* [x] dependsOn doesn't update when dependent store updates (#113)
* [x] window & requirejs examples no longer work with v0.9 (#169)
* [x] Don't auto set content-type if using FormData  (#140)
* [x] Fetch API compatibility (#133)

**Tasks**
* [x] Add support page (Similar to [React](http://facebook.github.io/react/support.html))
* [x] Update documentation (#153)
* [x] Fix marty-express tests
* [x] Update generator-marty
* [x] Update Marty Developer Tools jhollingworth/marty-devtools#7
* [x] Update Marty Chat Example to be isomorphic
* [x] Update Marty Chat Example to use ES6 classes https://github.com/jhollingworth/marty-chat-example-es6
* [x] Version documentation (#156)
* [x] Update [marty-todomvc](https://github.com/jhollingworth/marty-todomvc)
* [x] Blog

### CODE REVIEW

**Comment by dariocravero** [comment]
This looks like a very good step forward :). Need any help?
Also, should we make marty ES6-proof using something like Babel (previously [6to5](babeljs.io/blog/2015/02/15/not-born-to-die/)) if no native ES6 support is available?

**Comment by jhollingworth** [comment]
Hey, yeah would love some help :smile: Would you be interested in picking up #132? I was playing around with it the other day but got distracted...

Completely agree on Babel, I started [re-writing everything to be ES6 classes](https://github.com/jhollingworth/marty/tree/es6) the other day. It makes isomorphisim a whole load easier if everything's instantiatable. Things like ``Marty.createStore`` will still be supported but going to be adding ``Marty.register(SomeStore)`` for ES6. Hopefully will be done by next week...

**Comment by FoxxMD** [comment]
I'd be happy to help test when you need it :+1:

**Comment by dariocravero** [comment]
Good stuff! :) Will try to tackle #132 over the next few days. As for Babel, #138 might be a good a start. :) <3 to see an `es6` branch already! :)

**Comment by Dakuan** [comment]
This looks awesome - we are really hoping to use marty for new project but lack of server rending is a dealbreaker. Can pitch in some support testing things.

**Comment by dariocravero** [comment]
@jhollingworth quick one, have you considered migrating the testing suite to `jest`?

**Comment by jhollingworth** [comment]
Jest is cool however it would require converting all tests from mocha to jasmine plus. Also, I don't think it integrates well with SauceLabs (thats based on a quick google so could be wrong).

**Comment by dariocravero** [comment]
@jhollingworth on mocha/jest: facebook/jest#139

**Comment by Dakuan** [comment]
Just had a quick look at this to have a play with the server rendering but having some issues with webpack: 

First I got this sort of thing:

```
ERROR in ./~/marty/lib/actionCreators/actionCreators.js
Module parse failed: /Users/Dom/git/anu/node_modules/marty/lib/actionCreators/actionCreators.js Line 15: Unexpected reserved word
You may need an appropriate loader to handle this file type.
| }
|
| class ActionCreators {
```

which I'm guessing is the es6 stuff. I added `babel-loader` to my webpack config:

```
{
    test: /\.(es6|jsx|js)$/,
    loader: 'babel-loader'
}
```

which makes the errors go away - but breaks the `webpack-dev-server`. I see this in the browser console:
```
 Uncaught TypeError: Cannot use 'in' operator to search for 'document' in undefined
```

**Comment by jhollingworth** [comment]
@Dakuan does it tell you what line that error is thrown on?

**Comment by dariocravero** [comment]
@Dakuan can you paste your full `webpack.config.js`?

**Comment by Dakuan** [comment]
@jhollingworth line numbers don't seem all that useful...
```
util.load socket.io.js:294 
(anonymous function) socket.io.js:468 
(anonymous function) socket.io.js:3862 
(anonymous function) app.js:5244 
(anonymous function) bootstrap d51fae3c3136e0030930:508 
__webpack_require__ bootstrap d51fae3c3136e0030930:76 
fn index.js:1 
(anonymous function) bootstrap d51fae3c3136e0030930:508 
__webpack_require__ bootstrap d51fae3c3136e0030930:76
 fn client:1 
(anonymous function) client:65 
(anonymous function) bootstrap d51fae3c3136e0030930:508 
__webpack_require__ bootstrap d51fae3c3136e0030930:76 
fn app.js:539 
(anonymous function) bootstrap d51fae3c3136e0030930:508
 __webpack_require__ bootstrap d51fae3c3136e0030930:531 
(anonymous function) app.js:535
```
@dariocravero heres webpack:

```
var webpack = require('webpack'),
    path = require('path'),
    autoprefixer = require('autoprefixer-core'),
    ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    entry: [
        'webpack-dev-server/client?http://0.0.0.0:3000', // WebpackDevServer host and port
        'webpack/hot/only-dev-server',
        './src/client/app.jsx',
        './src/stylesheets/anu.less'
    ],
    output: {
        path: path.join(__dirname, '/build/'),
        filename: 'app.js'
    },
    devtool: '#inline-source-map',
    resolve: {
        extensions: ['', '.webpack.js', '.web.js', '.js', '.jsx', '.less']
    },
    module: {
        loaders: [{
            test: /\.jsx$/,
            loader: 'jsx-loader?harmony',
            exclude: /node_modules/
        }, {
            test: /\.less$/,
            loader: ExtractTextPlugin.extract("style-loader", "css-loader!less-loader!postcss-loader")
        }, {
            test: /\.(png|woff|woff2|eot|ttf|svg)$/,
            loader: 'url-loader?limit=100000'
        }, {
            test: /\.js/,
            loader: 'babel-loader'
        }]
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new ExtractTextPlugin("style.css", {
            allChunks: true
        })
    ],
    postcss: [autoprefixer]

};

```

**Comment by Dakuan** [comment]
Also, if I use webpack without hot swapping everything builds fine, but I get this in the browser:

```
Uncaught TypeError: Cannot read property 'register' of undefined actionCreators.js:216 

An error occured when dispatching a 'SET_ITEMS' action in  #setItems TypeError: Cannot read property '__id' of undefined {stack: (...), message: "Cannot read property '__id' of undefined"}
```

**Comment by Dakuan** [comment]
@jhollingworth @dariocravero 

managed to fix with this webpack config:

```
{
            test: /\.(jsx|es6|js)$/,
            loader: 'babel-loader',
            include: /(?=src)|(?=node_modules\/marty)/
        }
```

and by disabling the marty chrome plugin

**Comment by jhollingworth** [comment]
@Dakuan awesome! I going to start on a webpack demo soon so this will be useful :smile:

**Comment by jhollingworth** [comment]
Good point about Marty Developer Tools, have added it to the list of things to look at. Thanks

**Comment by Dakuan** [comment]
Yep! Some progress but not out of the woods yet. When trying to require (on the server) a file that is connected with the marty app eg some kind of entry point like `app.jsx` or `routes.jsx` you get an error as node wont like the `class` keyword being out of place.

A natural thing to do is to try and use the babel require polyfill from herehttps://babeljs.io/docs/usage/require/ . This still won't work yet as marty is ignored by babel due to it being in `node_modules`. That's easily fixed by adding the `{ignore: true}` flag to the babel config. It's dog slow first time - hopefully whitelisting marty rather than just allowing all the npm modules to be parsed will help, but it's not working as documented at the moment.

Anyway, that spins for a while and then we get:

```
-> node src/server/index.js

/Users/Dom/git/anu/node_modules/marty/node_modules/underscore/underscore.js:1536
}.call(this));
  ^
TypeError: Cannot read property '_' of undefined
    at /Users/Dom/git/anu/node_modules/marty/node_modules/underscore/underscore.js:15:32
    at Object.<anonymous> (/Users/Dom/git/anu/node_modules/marty/node_modules/underscore/underscore.js:1536:3)
    at Module._compile (module.js:456:26)
    at normalLoader (/Users/Dom/git/anu/node_modules/babel/lib/babel/api/register/node.js:102:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Dom/git/anu/node_modules/babel/lib/babel/api/register/node.js:115:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Dom/git/anu/node_modules/marty/index.js:4:9)
```

Here is how I get babel running:
```
// index.js 

require("babel/register")({
    ignore: false
});

var app = require('./app');

// 4130 is a steel alloy. It's what you make BMX frames out of.
app.listen(process.env.PORT || 4130, function() {
    console.log('listening on *:4130');
});
```

**Comment by Dakuan** [comment]
I should add that babel appears to be otherwise working, this test es6 class works as expected:

```es6
class Thing {
	log () {
		console.log('mew');
	}
}


module.exports = Thing;
```

**Comment by dariocravero** [comment]
I was about to suggest `babel` as I was reading the thread on my email @Dakuan and then saw your last comment :).
You can always pipe your code thorugh `babel-node`; `iojs` might also be a better target than `node` going forward.

**Comment by Dakuan** [comment]
Which package do you mean? Can't seem to find it here: https://www.npmjs.com/search?q=babel-node

**Comment by dariocravero** [comment]
It's a binary that [babel installs](https://babeljs.io/docs/usage/cli/#babel-node)

**Comment by jhollingworth** [comment]
It might be easier if node consumes the built files rather than having to get people to add shims or use different JS environments. Although that has the downside of making it slightly more painful to debug

**Comment by Dakuan** [comment]
Yeah I tried requiring `dist/marty` but I got a babel error:

``` javascript
require("babel/register")({
    ignore: false
});

var app = require('./app');
```
 gives:

```
/Users/Dom/git/anu/node_modules/marty/dist/marty.js:3241
global._babelPolyfill = true;
^
Error: only one instance of babel/polyfill is allowed
    at Object.<anonymous> (/Users/Dom/git/anu/node_modules/marty/dist/marty.js:3241:1)
    at Object.core-js/shim (/Users/Dom/git/anu/node_modules/marty/dist/marty.js:3246:66)
    at s (/Users/Dom/git/anu/node_modules/marty/dist/marty.js:1:637)
    at /Users/Dom/git/anu/node_modules/marty/dist/marty.js:1:679
    at Object.../../polyfill (/Users/Dom/git/anu/node_modules/marty/dist/marty.js:3234:30)
    at s (/Users/Dom/git/anu/node_modules/marty/dist/marty.js:1:637)
    at /Users/Dom/git/anu/node_modules/marty/dist/marty.js:1:679
    at Object../lib/babel/api/register/node (/Users/Dom/git/anu/node_modules/marty/dist/marty.js:5690:4)
    at s (/Users/Dom/git/anu/node_modules/marty/dist/marty.js:1:637)
    at /Users/Dom/git/anu/node_modules/marty/dist/marty.js:1:679
```

and without babel:

``` javascript
// require("babel/register")({
//     ignore: false
// });

var app = require('./app');
```

gives:

```
 -> node src/server/index.js

/Users/Dom/git/anu/node_modules/marty/dist/marty.js:7344
  if (self.fetch) {
      ^
ReferenceError: self is not defined
    at /Users/Dom/git/anu/node_modules/marty/dist/marty.js:7344:7
    at Object.<anonymous> (/Users/Dom/git/anu/node_modules/marty/dist/marty.js:7664:3)
    at s (/Users/Dom/git/anu/node_modules/marty/dist/marty.js:1:639)
    at /Users/Dom/git/anu/node_modules/marty/dist/marty.js:1:690
    at Object.whatwg-fetch (/Users/Dom/git/anu/node_modules/marty/dist/marty.js:7667:1)
    at s (/Users/Dom/git/anu/node_modules/marty/dist/marty.js:1:639)
    at /Users/Dom/git/anu/node_modules/marty/dist/marty.js:1:690
    at Object.../../http/hooks/parseJSON (/Users/Dom/git/anu/node_modules/marty/dist/marty.js:1762:1)
    at s (/Users/Dom/git/anu/node_modules/marty/dist/marty.js:1:639)
    at /Users/Dom/git/anu/node_modules/marty/dist/marty.js:1:690
```

**Comment by Dakuan** [comment]
I'm wondering if es6 is more trouble than its worth for a lib that wants to be able to run anywhere. :crying_cat_face:

**Comment by jhollingworth** [comment]
I've thought the same a few times recently... Once [Marty.Component](https://github.com/jhollingworth/marty/pull/147) is done I'm going to focus on simplifying getting it to work on node. Hopefully this will be much better next week! 

Thanks for all you're help trying this out, very much appreciated!

**Comment by oliverwoodings** [comment]
@jhollingworth could we add another dist output that is precompiled into ES5? By default marty could be es5, but if you want to use ES6 you could do require("marty/es6") or something

**Comment by jhollingworth** [comment]
We're feature complete on this release so I've publish [Marty v0.9.0-rc1](https://www.npmjs.com/package/marty). I've updated the [chat example](https://github.com/jhollingworth/marty-chat-example/tree/v0.9) (including isomorphism) if anyone is interested in what it looks like

**Comment by dariocravero** [comment]
Brilliant!! :) It's going to be an amazing release!

I was wondering if it should actually be `1.0.0` as it does include a fairly good amount of changes (despite the old mode just being deprecated). What would your plans for a `1.0.0` release be otherwise?

I'm working on a _fully class-ified_ structure right now, will put that up as an example too. Will have a look at the chat example later on today and comment on it.

**Comment by jhollingworth** [comment]
Good point about v1.0. My only concern is React isn't stable yet so we might have to change the APIs (e.g. How we use contexts). Maybe it's worth waiting until React 1.0 comes out?

**Comment by dariocravero** [comment]
Good stuff :) In all fairness, `0.9.0` add functionality and is still backwards compatible, so it's alright :)

**Comment by jhollingworth** [comment]
Last major blocker (beyond pending tasks) is react-router v0.13 rackt/react-router#638

**Comment by dariocravero** [comment]
On that: #186 :). The way I see it, an agnostic framework wouldn't make assumptions as to what routing you want to use. Therefore `react-router` shouldn't be enforced and should be hidden behind a facade that allows any router to be plugged in. Am I wrong to think that marty might be better off being agnostic to have greater acceptance/usage and granularity? Thoughts?

**Comment by jhollingworth** [comment]
Oh completely. its just that [marty-express](https://github.com/jhollingworth/marty-express) currently only works with react-router (although plan is to allow any router to integrate). Isomorphisim is one of the major features for v0.9 so want everything working together before I release

**Comment by dariocravero** [comment]
Class! Good to know it was already on your mind too :) I'm glad to help towards getting the next version on a modular approach if that's desirable

**Comment by FoxxMD** [comment]
Along with #153 and #156 I'd like to add that there should be an `UPGRADING.md` document (or include in one of the docs) in the case that there are any breaking changes between 0.8 and 0.9.

**Comment by dariocravero** [comment]
I'll be running an upgrade over the next few weeks (probably next week) on
a fairly large 0.8 project to 0.9 with classes. I think I should be able to
create a guide out of that documenting the process and any gotchas in
between. It shouldn't really break anything with your current code though.

**Comment by FoxxMD** [comment]
Thanks @dariocravero that'd be awesome :+1:

**Comment by jhollingworth** [comment]
I've just finished a big update to Marty DevTools. Load of bug fixes, immutable.js support, a better view on the data plus the ability to revert actions

**Comment by jhollingworth** [comment]
v0.9 docs are available here http://martyjs.org/v/0.9.0-rc2/

**Comment by dariocravero** [comment]
@FoxxMD [ere's a rough guide (by example)](https://gist.github.com/dariocravero/2ea4308946c15f2da1af). Will try to write it up a bit better these days.

**Comment by FoxxMD** [comment]
thanks!

**Pull request merged**
